image:
  image: ghcr.io/leo-alvarenga/leoalvarenga-dev
  tag: latest

service:
  port: 5000

nightly:
  enabled: true
  service:
    port: 5001
  image:
    image: ghcr.io/leo-alvarenga/leoalvarenga-dev
    tag: latest-nightly

