
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.name.nightly" . }}
spec:
  selector:
    {{- if .Values.nightly.enabled }}
    {{- include "portfolio.labels.nightly" . | nindent 4 }}
    {{- else }}
    {{- include "portfolio.labels" . | nindent 4 }}
    {{- end }}
  type: LoadBalancer
  ports:
  - name: {{ include "portfolio.name.nightly" . }}
    port: {{ .Values.nightly.service.port }}
    targetPort: 80

