# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.name }}
spec:
  selector:
    app: {{ .Release.name }}
  type: ClusterIP
  ports:
  - name: {{ .Release.name }}
    protocol: 
    port: 80
    targetPort: {{ .Values.service.targetPort }}

