apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.name" . }}
spec:
  selector:
    {{- include "portfolio.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - name: {{ include "portfolio.name" . }}
    protocol: 
    port: 80
    targetPort: {{ .Values.service.targetPort }}

